version: '3'

services: 
  product-services:
  bulid: ./product-services
  volumes:
    - ./product:/usr/src/app
    parts:
      - 5001:80

      websitr:
        image: php:apache
        volumes:
          - ./website:/var/www/html
          parts:
            - 5000:80
            depends_on:
              - product-service
              

